### ISSUE TITLE
PMtest() error

### ISSUE THREAD

**Issue by sharovaa** [LAPKB/Pmetrics#107]
After successful download of Pmetrics 2.0.0 and successfully running PMbuild(), PMtest() throws the following error:

> PMtest()
Error in -ncol(data) : invalid argument to unary operator
In addition: Warning message:
In data(mdata.1, envir = environment()) : data set ‘mdata.1’ not found

**Comment by mnneely** [comment]
Thanks for pointing this out. We'll get it fixed in the ongoing beta version which has the latest builds. That is the "v2_dev" branch. It can always be installed using:

`devtools::install_github(“LAPKB/Pmetrics”, ref = “v2_dev”)`

Stay tuned for the fix.

**Comment by Siel** [comment]
The fix has been uploaded to v2_dev. Could you verify if it is working now? if that is the case, we will proceed to merge it with master in the next couple of days

**Comment by sharovaa** [comment]
Yes, it's working now! Thank you! I got:

> PMtest()
Congratulations; you have successfully installed all components of Pmetrics.

**Comment by Siel** [comment]
That is great, I'm closing the issue now. This fix will be is scheduled to be released with the next minor patch to Pmetrics.
