### ISSUE TITLE
MM_opt error

### ISSUE THREAD

**Issue by sharovaa** [LAPKB/Pmetrics#114]
Running MM_opt throws the following error:

>   MM_opt(poppar=final.58, 
+          model="model58.txt", 
+          data= "ov2test.csv", 
+          nsamp=1,
+          weight=list(auc=1),
+          predInt=c(41, 47.75, 0.25), 
+          outeq=1)

DATA STANDARDIZATION REPORT:

 Data are in full format already.

DATA VALIDATION REPORT:

No data errors found.

FIX DATA REPORT:

There were no errors to fix in you data file.
DATA STANDARDIZATION REPORT:

 Data are in full format already.

DATA VALIDATION REPORT:

No data errors found.

FIX DATA REPORT:

There were no errors to fix in you data file.
Error in `[.data.frame`(x, order(x, na.last = na.last, decreasing = decreasing)) : 
  undefined columns selected
In addition: Warning messages:
1: In xtfrm.data.frame(x) : cannot xtfrm data frames
2: In xtfrm.data.frame(x) : cannot xtfrm data frames

Traceback shows the following:
> traceback()
8: stop("undefined columns selected")
7: `[.data.frame`(x, order(x, na.last = na.last, decreasing = decreasing))
6: x[order(x, na.last = na.last, decreasing = decreasing)]
5: sort.default(pop.weight)
4: sort(pop.weight)
3: getSimPrior(i)
2: SIMrun(poppar = poppar, model = model, data = data, nsim = 0, 
       predInt = predInt, obsNoise = NA, outname = "MMsim", quiet = T, 
       ...)
1: MM_opt(poppar = final.58, model = "model58.txt", data = "ov2test.csv", 
       nsamp = 1, weight = list(auc = 1), predInt = c(41, 47.75, 
           0.25), outeq = 1)

**Comment by mnneely** [comment]
Thanks for pointing out. It was a problem in parsing the model file with fixed gamma/lambda. I believe this is now fixed in the current beta version available in the "v2_dev" branch. Install with devtools::install_github("LAPKB/Pmetrics@v2_dev").
