### ISSUE TITLE
Segmentation fault on finished run

### ISSUE THREAD

**Issue by mhovd** [LAPKB/Pmetrics#12]
This is an issue that I have had over the last couple of days, following upgrading to 1.9.4 on MacOS 15.4 (now 15.5). The issue might also have been present on 1.9.3.

```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x1767889ac
#1  0x176787d53
#2  0x7fff7089b5fc
#3  0x10c8105f6
#4  0x10c83762f
#5  0x10c843dba
#6  0x10c84a842
#7  0x10c84ba1e
/Users/mhovd/Rosuvastatin/Runs/351/npscript: line 8: 91143 Segmentation fault: 11  ./np_run < go

Cleaning up....

Loading required package: Pmetrics
Error in if (success) { : argument is of length zero
Calls: PMreport
Execution halted
```

The run is done on my MacBook, but the project directory is on an OSXFUSE SSHFS network volume, which works nicely most of the time. The error happens after the run converges and finishes, and after printing the estimates for patient 5 out of 57.

**Comment by Siel** [comment]
Are you getting that error with with simpler models also? what I see is that is a problem generating the html report.

**Comment by mhovd** [comment]
On further inspection, this seems to be a model-specific issue, as other models run just fine.
Additionally, the error is not present for some sets of boundaries, as I am able to run a previous version of it. Larger boundaries seem fine, but reducing them seems to cause the issue.

In OUTT0001, the file is cutoff halfway in writing the correlation matrix.

**Comment by mnneely** [comment]
I see this error now only when a run crashes.  If you look carefully at the Terminal/DOS window (scrolling up), you might find more information about the error associated with the smaller boundaries.

**Comment by mhovd** [comment]
I couldn't find anything out of the ordinary in the terminal output.
Nevertheless, I've attached it here, in case you see something that I've missed. Cycles removed due to size.
[run_output.txt](https://github.com/LAPKB/Pmetrics/files/4715678/run_output.txt)

**Comment by mnneely** [comment]
It seems like it was a problem with subject 5.  The program crashed trying to report statistics for the posterior distribution of parameter SC.  If the problem is specific to a particular model or parameter range, while vexing, indicates an inappropriate model for the data.  If you can get past this by adjusting ranges, it isn't a bug, but perhaps we can improve error reporting!

**Comment by mhovd** [comment]
That definitely seems to be the case, as it is only an issue with that specific model that may also be resolved by increasing the boundaries. 
Is there any reason why it would fail during the reporting, but not during cycling?
Either way, a more concise error would be much appreciated (even though it does say that PMreport was the call).
