### ISSUE TITLE
Model library in R

### ISSUE THREAD

**Issue by mhovd** [LAPKB/Pmetrics#120]
Several models are available in the LAPK [model library](http://www.lapk.org/ModelLib.php).
Would it be possible to have these available in R?
I suggest a library function, e.g. `modelLibrary`, which takes an argument specifying the desired model.
This would further simply the workflow once a dataset has been imported in to R, and I image one could be able to then use
```
mod = PM_model$new(modelLibrary("1comp"))
```
If needed, one can then (as usual) update the model with `mod$update()`.

Would this be feasible?

**Comment by Siel** [comment]
It is feasible. I'm going to start drafting it over a new PR so we can further discuss it.

**Comment by mnneely** [comment]
This is implemented now. The library is most accessible via the model builder app (`build_model()`). It is also a data object in Pmetrics: `modelLibrary`. In the future, we’ll allow users to add their own models to personal libraries.
