### ISSUE TITLE
Remove bloat following run

### ISSUE THREAD

**Issue by mhovd** [LAPKB/Pmetrics#123]
Following a run (Pmetrics 2.0.1), seemingly during the step generating the report, an object is printed to the terminal.
Here is an example:

In R
```
library(Pmetrics)
fit = PM_fit$new(model = NPex$model, data = NPex$data)
fit$run()
```

Then in the terminal, when the run has finished, the following shows
```
...
The following objects have been saved:

NPdata: All output from NPAG
pop: Population predictions at regular, frequent intervals
post: Posterior predictions at regular, frequent inteverals
final: Final cycle parameters and summary statistics
cycle: Cycle information
op: Observed vs. population and posterior predicted
cov: Individual covariates and Bayesian posterior parameters
mdata: The data file used for the run
          Ka         Ke         V      Tlag1       prob
1  0.8999440 0.04310272 108.64920 2.09592004 0.05000771
2  0.2151984 0.08328365  35.22432 1.80379203 0.10419106
3  0.7927824 0.04393907 101.57052 0.88691202 0.04985577
[rest of output removed]
```

It looks like a `final` object, followed by a summary of said object, with reported mean, sd, etc.
This bloat makes it difficult to view the run summary that is otherwise informative.

**Comment by Siel** [comment]
The initial messages are generated here: https://github.com/LAPKB/Pmetrics/blob/8284592f2fc3d6cd3a4d6b2d9f78c4a587b31a9d/R/PMreport.R#L330

The second print, might be because of: https://github.com/LAPKB/Pmetrics/blob/8284592f2fc3d6cd3a4d6b2d9f78c4a587b31a9d/R/PMreport.R#L365

Should we remove those?

**Comment by mhovd** [comment]
The information following line 330 is important to keep, as its informative.
But the output of `print(df)` on line 365 can be considered removed. I can try to remove it locally and see if that resolves my issue.
