### ISSUE TITLE
Predictions at non-concentration times do not load into R?

### ISSUE THREAD

**Issue by aasberg** [LAPKB/Pmetrics#13]
Following a run with a complex model I only get predicted concentrations at the time of measured concentrations and not every 0.2 hours as according to NPrun(..., idelta=12). The predictions are present in the PRTB0001 file, but dose not appear in the post.4 file in R or when plotting individual plots; plot(mdata.4, pred=post.4, ...).

**Comment by mnneely** [comment]
Will look into that.  The predictions in the post.x object should be at observation times and regular intervals governed by the idelta argument to NPrun(), which is 12 by default, i.e. predictions every 12 minutes or 5 per hour.

**Comment by mnneely** [comment]
Can you reinstall Pmetrics try again? It seems to be working ok on my end.
In Rstudio, use the following:

`devtools::install_github("LAPKB/Pmetrics")`

**Comment by aasberg** [comment]
Nope…. did not solve it I am afraid!

/Anders

**Comment by mnneely** [comment]
I've just updated Pmetrics to 1.9.6 to deal with another bug related to a new version of dplyr.  Can you make sure you're running 1.9.6 and see if this works now? It is still working on my end.

**Comment by aasberg** [comment]
The new version does not install. Also seems to have something with dplyr to do:

_Error: object ‘as.tbl_cube’ is not exported by 'namespace:dplyr'
Execution halted
ERROR: lazy loading failed for package ‘Pmetrics’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Pmetrics’
Error: Failed to install 'Pmetrics' from GitHub:_

**Comment by Siel** [comment]
I also got the same error 
`
Error: object 'as.tbl_cube' is not exported by 'namespace:dplyr'
Execution halted
ERROR: lazy loading failed for package 'Pmetrics'
* removing 'C:/Users/siel/Documents/R/win-library/3.6/Pmetrics'
Error: Failed to install 'Pmetrics' from GitHub:
  (converted from warning) installation of package 'C:/Users/siel/AppData/Local/Temp/RtmpcdaTvM/file85a45a07407e/Pmetrics_1.9.6.tar.gz' had non-zero exit status
`

**Comment by Siel** [comment]
@aasberg I just uploaded a fix, try again please :)

**Comment by mnneely** [comment]
Ah, the issue was that the Namespace file which controls package lookup for functions hadn't updated properly.  Let's hope Julian's fix now gets past this.

**Comment by aasberg** [comment]
Thanks Julian! Pmetrics installed now. So good to have guys like you to fix these things so I can focus on using it ;)

However, the new version did not fix the post.x problem. I have to use the makePost(x) to get all predictions loaded for plotting.

**Comment by Siel** [comment]
Thanks @aasberg but it was professor @mnneely's fix, I just polished it a little bit. 👍

**Comment by mnneely** [comment]
I can't reproduce the error now Anders. v1.9.6 is running fine on my machine. As you can see from the screen shot, on run 6, using your input files on my machine, I get a prediction at time 0.17 and also 0, 0.2, 0.4, 0.6, 0.8,... hours as expected.  

Just as a quick test, here's what I ran:
`NPrun(data = "mpadev.csv", model = "2c2gbe.txt", indpts = 3, cycles = 3)`

<img width="396" alt="image" src="https://user-images.githubusercontent.com/8136142/84312387-b6586580-ab19-11ea-86bf-fc7a665998a3.png">

Can you make sure you quit Rstudio, restart, load Pmetrics, and try the above command?

**Comment by aasberg** [comment]
My wrong, IT WORKS :)
Thanks Michael!

**Comment by mnneely** [comment]
Whew! :) Closing this issue!
