### ISSUE TITLE
PMfit run, npscript does not execute

### ISSUE THREAD

**Issue by masyamada** [LAPKB/Pmetrics#138]
fit3 <- PM_fit$new(dat3, mod3)
   fit3$run()

Creates a new run folder; but npscript must be started manually from the command line. Pmetrics branch = v2_dev

macOS Monterey (Version 12.4)
Apple M1, 2020
Fully brewed (R, Rstudio, etc.).   All required R packages for Pmetrics are updated.

**Comment by Siel** [comment]
I'm setting up my environment to be able to test it.

**Comment by Siel** [comment]
Already documented error using M1 chip. Need more testing

**Comment by Siel** [comment]
Closing, as is not a Pmetrics Issue.
