### ISSUE TITLE
Error in MakeCov

### ISSUE THREAD

**Issue by Siel** [LAPKB/Pmetrics#139]
When there is only one subject and one set of covariates, this line https://github.com/LAPKB/Pmetrics/blob/73cfe66327766659210f3f87ac613bb53c9b1cfe/R/makeCov.R#L37 is causing the 'cov' to be transposed. That causes this line https://github.com/LAPKB/Pmetrics/blob/73cfe66327766659210f3f87ac613bb53c9b1cfe/R/makeCov.R#L46 to error because of a size mismatch.

Reported by @mhovd

**Comment by mhovd** [comment]
Here is an example of data that will reproduce the error, note that only the first observation has covariates, the rest should be carried forward (but isn't)

```r
id evid time dur dose addl ii input  out outeq c0 c1 c2 c3 wt txt  hct ssconc sex hgt
1    1    0   0 7000   -1 12     1   NA    NA NA NA NA NA 84  30 0.29      5   1 190
1    0    0  NA   NA   NA NA    NA  5.0     1 NA NA NA NA NA  NA   NA     NA  NA  NA
1    0    1  NA   NA   NA NA    NA 17.0     1 NA NA NA NA NA  NA   NA     NA  NA  NA
1    0    3  NA   NA   NA NA    NA 11.9     1 NA NA NA NA NA  NA   NA     NA  NA  NA
```
