### ISSUE TITLE
Na pred values are being generated

### ISSUE THREAD

**Issue by Siel** [LAPKB/Pmetrics#140]
@mhovd shared a dataset in which for NA pred values are being generated. This is causing op$plot to crash

**Comment by Siel** [comment]
@mhovd Could you please explain me what is the intended behavior of this line in the datafile?

#ID| EVID | TIME | DUR | DOSE | ADDL | II | INPUT | OUT
-- | -- | -- | -- | -- | -- | -- | -- | --
81.2 | 1 | 0 | 0 | 8000 | . | 24 | 1 | .



Specifically why II=24 if we're missing ADDL. This might not be related with the issue, but it's behavior is undetermined.

**Comment by mhovd** [comment]
> Specifically why II=24 if we're missing ADDL. This might not be related with the issue, but it's behavior is undetermined.

That appears to be a mistake, in this case, `ADDL` should be `-1` in this case.

**Comment by mhovd** [comment]
On further inspection of the dataset, `II` always has an entry when a dose is given, without any entries in `ADDL`.
This is likely an error in the dataset, especially for doses given at time after zero, e.g. additional, manual doses.

**Comment by mhovd** [comment]
The error was likely due to an erroneous dataset, closing as it does not provide learning value or actionable items.
