### ISSUE TITLE
Residual Op plots fail with Error

### ISSUE THREAD

**Issue by RyanArmiger** [LAPKB/Pmetrics#155]
Hi,

When trying to run op plots with `run$op$plot(resid = T)`, I receive the error:
`Error in modifyList(default_font, default) : is.list(val) is not TRUE`

With default or explicitly set `resid = F` it plots fine. 

This was occurring on Pmetrics_2.0.0. I have updated to R version 4.2.2 and Pmetrics_2.0.2 and this is still occurring. 
This did not happen on the version I was running prior to 2.0.0, but I am unsure of what that version was.

If relevant, I am using a Mac.

Thanks

**Comment by mnneely** [comment]
Thanks for reporting. I've identified the bug and will get the fix pushed to v2_dev branch.

**Comment by mnneely** [comment]
Fix pushed to v2_dev branch.
