### ISSUE TITLE
Error in running model (....$run and NPrun() )

### ISSUE THREAD

**Issue by islay76** [LAPKB/Pmetrics#158]
Hello everyone, 
When I try to run a model, there is the following error statement : 

### 
Creating model file at: genmodel.txt
Error in instr[getNext(instr)] <- ab : 
  incompatible types (from closure to character) in subassignment type fix 
### 

There is no apparent error in the data or model files when I check with PM_fit$check(), the script I used is : 
### 
> setPMoptions(sep = ";",dec = ".")
> data1<-PM_data$new("C:/xxx/data30m.csv")
> mod1 <- PM_model$new("C:/xxx/modeltry.txt")
> fit1 <- PM_fit$new(data1, mod1)
> fit1$check()
> fit1$run() 
### 

Thanks

**Comment by Siel** [comment]
Hello @islay76 ,

Did the program show any error when building the model or error_files?
Is it possible for you to share your model.txt? So I can try it locally?

Thanks!

**Comment by islay76** [comment]
Of course, 
Here is the model : 


#Pri
Ke, 0.495
V, 38.4

#Out
Y(1) = X(1)/V

#Err
L=0.1
0.1,0.1,0,0


The program didn't show any error when building the model 
Thanks

**Comment by Siel** [comment]
I just checked and that model is bulding just fine for me, which version of Pmetrics do you have installed?
