### ISSUE TITLE
PTA analysis code

### ISSUE THREAD

**Issue by harishkaushikbugworks** [LAPKB/Pmetrics#160]
Hello Neely,

I have a drug whose POPPK is fit to a 2-compartment IV infusion model and wanted to perform PTA analysis using PMetrics, could you or anyone help in sharing the model code or any tutorial to understand, it will be of great help

Regards
Harish

**Comment by Siel** [comment]
Hello @harishkaushikbugworks.

Pmetrics comes with a built-in tutorial that teach you all the basics including PTAs. After loading Pmetrics use PM_tutorial() to start the script and follow the prompts.

I'm closing this issue, but feel free to reopen it if you need further assistance.
