### ISSUE TITLE
PTA on output values

### ISSUE THREAD

**Issue by PKPDICU** [LAPKB/Pmetrics#161]
Hello,
I would like to do a PTA analysis but on the **observed** data (column "out" of the data file) 
My objective is to obtain the time spent > MIC, the ratio Cmin/ MIC, for each of the **measured** concentration profiles 
Is it possible with Pmetrics and if so, could someone tell me how to do it? 
Thanks a lot

**Comment by masyamada** [comment]
Hi PKPDICU, It sounds like you want to do a PTA analysis without first creating the PK population model.  The PTA analysis in Pmetrics assumes you have a PK population model in hand. So, I don't think Pmetrics can do what you desire.

**Comment by Siel** [comment]
Hi @PKPDICU,
As @masyamada said, Pmetrics needs a model to be able to perform the simulations needed to calculate a PTA, you can create a model based on your data (out column of the data file), and then use it to calculate the PTA.

There are an example in PM_tutorial() that shows how to fit a population model from the data and then a PTA from the population model.

In the mean time, I'm going to close this issue, feel free to reopen it if you have further questions.
