### ISSUE TITLE
Error in do_one(nmeth) : NA/NaN/Inf in foreign function call (arg 1) In addition: Warning message: In storage.mode(x) <- "double" : NAs introduced by coercion

### ISSUE THREAD

**Issue by Larubei** [LAPKB/Pmetrics#166]
Hello 
When I execute Res$validate() command, this message appears: 

_Error in do_one(nmeth) : NA/NaN/Inf in foreign function call (arg 1) In addition: Warning message: In storage.mode(x) <- "double" : NAs introduced by coercion_

Is the problem due to an insufficient number of individuals in my dataset? Or maybe the output per individual? Or the setting of the limits? 
Thanks in advance for your help

**Comment by Larubei** [comment]
Finally it was due to the non-numerical reporting of "ID" in my data, as mentionned in previous issues

**Comment by Siel** [comment]
Thanks for the report!
