### ISSUE TITLE
PMmb2csv {Pmetrics} error

### ISSUE THREAD

**Issue by njrhodes** [LAPKB/Pmetrics#17]
I am attempting to use the PMmb2csv function but I get an error. The exe is generated along with a tempControl file, but the data.csv file is not created. Syntax below:

`PMmb2csv("JM_061720_NJR.mb2", newFile = "data")`

> Error in system(cmd, intern = intern, wait = wait | intern, show.output.on.console = wait,  : 
> formal argument "show.output.on.console" matched by multiple actual arguments

Here is my sessionInfo:

> sessionInfo()
> R version 3.5.1 (2018-07-02)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] rjson_0.2.20   Pmetrics_1.5.2
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.5.1 tools_3.5.1    yaml_2.2.1

**Comment by Siel** [comment]
Hi @njrhodes I would like to help you with this issue, can I have more information? like the current version of pmetrics you are using or maybe a portion of the source files to try to reproduce this behaviour on my end?

Thanks!

**Comment by njrhodes** [comment]
hi @Siel. The version I use is 1.5.2 and I will zip you the problematic files.
[mb2csv.zip](https://github.com/LAPKB/Pmetrics/files/4834154/mb2csv.zip)

**Comment by mnneely** [comment]
Hi @njrhodes,  This file format is actually .mb2, which was an old BestDose file format.  The function works only to convert .mb files.  I apologize for name confusion, but the function is meant to convey "MB to CSV" in the name, not "MB2 CSV".  We have no function to covert .mb2 files to Pmetrics.  Your best bet is to use the old Windows executable standalone BestDose, and Pastrx to open each .mb2 file, then save it as a .wrk file.  Then use PMwrk2csv in Pmetrics.  The other option is to manually do it. :(

**Comment by njrhodes** [comment]
Hi @mnneely, No worries. thanks for taking a look.

I came up with a work around that produces a close to workable file, thought it needs manual cleaning still. This works for batch conversion too. LMK if interested, but here is the code. Maybe someone who is better at coding than me can turn it into a fully valid function for those of us with old mb2 files who would like to go back and use them for pop modeling.

Thanks!

```
as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}

library(stringr)
library(stringi)
library(filesstrings)
library(lubridate)
library(gsubfn)
library(mefa)

path <- getwd()

#files <- list.files(pattern="*.mb2.txt")
#newfiles <- gsub(".txt$", "", files)
#file.rename(files, newfiles)

##Merge all dosing records together to parse them together

out.file<-""
file.names <- dir(path, pattern =".mb2")
for(i in 1:length(file.names)){
  file <- read.table(file.names[i],header=FALSE, sep=";", stringsAsFactors=FALSE)
  out.file <- rbind(out.file, file)
}

write.table(out.file, file = "comb_data.txt",sep=";", 
            row.names = FALSE, quote=FALSE, col.names=F, fileEncoding="windows-1252")

##Read unified file

data_raw <- stri_read_lines("comb_data.txt")

##Extract the unique id numbers

id.number <- (
  as.data.frame(
  unlist(
    str_replace(
      str_squish(
        str_extract(string = data_raw, pattern = ".{32}(?=[MF]N Unknown)")
        ),
      " ","")
      )
    )
  )

head(id.number)
nrow(id.number)
nrow(na.omit(id.number))
list(na.omit(id.number))

#Replace first missing value and change variable name to id to fill down
fix(id.number)
id.number <- fill.na(id.number)

data_raw <- data.frame(id.number,data_raw,stringsAsFactors = FALSE)

data_dose <- data_raw[grep(" IV  ", data_raw$data_raw),]

id <- data_dose$id.number

doserec <- na.omit(
  as.data.frame(
    unlist(
      strsplit(
        str_squish(
          str_replace(
            str_extract(string = data_dose[,2], pattern = "(?<=\\  IV  ).*"),
            "\\*{2}|\\*","")
        )," ")
      )
    )
  )

tail(doserec)

nrow(doserec)

date <- na.omit(
    unlist(
        str_extract(string = data_dose[,2], pattern = ".{16}(?=\\  IV  )")
        )
      )

date <- as.data.frame(strptime(date, format = "%Y/%m/%d %H:%M"),tz=""); colnames(date) <- "date"

dur <- unlist(doserec[seq(2,nrow(doserec),4),])

dur <- as.data.frame(as.numeric.factor(dur)); colnames(dur) <- "dur"

dose <- unlist(doserec[seq(3,nrow(doserec),4),])

dose <- as.data.frame(as.numeric.factor(dose));colnames(dose) <- "dose"

crcl <- unlist(doserec[seq(4,nrow(doserec),4),])

crcl <- as.data.frame(as.numeric.factor(crcl));colnames(crcl) <- "crcl"

dose.data <- data.frame(id,dur,dose,crcl,date)

head(dose.data)

##Extract the other observations and reset ID based on the rows meeting criteria

data_obs <- data_raw[grep("!Date-time, value, comment", data_raw$data_raw),]

id <- data_obs$id.number

nrow(id)

obs <- na.omit(
  as.data.frame(
    unlist(
      strsplit(
        str_squish(
          str_extract(string = data_obs[,2], pattern = ".*(?=\\!Date-time, value, comment)")
            )," ")
      )
    )
  )

observations <- unlist(obs[seq(3,nrow(obs),3),])

observations <- as.data.frame(as.numeric.factor(observations));colnames(observations) <- "observations"

date <- paste(unlist(obs[seq(1,nrow(obs),3),]),unlist(obs[seq(2,nrow(obs),3),]),sep= " ")

date <- as.data.frame(strptime(date, format = "%Y/%m/%d %H:%M"),tz=""); colnames(date) <- "date"

obs <- data.frame(id,observations,date)

data <- merge(dose.data,obs,by=c("id","date"),all=TRUE)

write.csv(data,"data.csv")

```
