### ISSUE TITLE
Interactive PM_data generator for simulations

### ISSUE THREAD

**Issue by OmarAshkar** [LAPKB/Pmetrics#172]
Hello, 

I see the only way to run simulation is to refer to PM_data object or PM formatted file. It would be easier to have a function that would generate the administration events from within R and pipe it to `PM_data`.

Also, I am not sure of observations are specified from predInt argument in `PM_results$sim()` or also in from the events data.

Thank you!

**Comment by mnneely** [comment]
Your suggestion, if I understand correctly, is essentially to make a data object (which serves as the administration/observation template for simulations) in R. I'm open to the idea, but do you have more specific suggestions on how you'd like to see that implemented?

Simulated outputs will be generated at all times defined by `predInt` and also any observation times in the template that might be outside a `predInt` time. If there are times in the template that are also `predInt` times, Pmetrics will not simulate a double value.

**Comment by OmarAshkar** [comment]
@mnneely Yes, a dummy code will be like:

```
events <- PM_data$initialize() %>%   # create empty object
               PM_event(amt = 20, addl = 12, II = 12, start = 0) %>% 
PM_event(amt = 10, addl = 12, II = 24, start = 48)
```
So it will simply append to the created object.

Does this makes sense?!

**Comment by mnneely** [comment]
Nice idea. Let me work on developing that. I like the piping part of it especially. Very tidyverse. :)

**Comment by mnneely** [comment]
This has now been implemented. It is currently in the dev branch. In keeping with the R6 framework, `PM_data` objects have a new method `addEvent()`, which can be chained, similar to piping.

For example: `dat <- PM_data$new()$addEvent(id = 1, time = 0, dose = 100)$addEvent(id = 1, time = 6, out = -1)`

In R, for readability, you can also put field or method calls on new lines:

```
dat <- PM_data$new()$
addEvent(…)$
addEvent(…)
```

Thanks for the suggestion. Full documentation is in the help for `PM_data`.
