### ISSUE TITLE
Unable to set custom Fortran statement using PMFortranConfig()

### ISSUE THREAD

**Issue by mhovd** [LAPKB/Pmetrics#18]
When attempting to choose a custom Fortran compiler statement using PMFortranConfig, option 5, PMetrics automatically chooses the standard. 
```
gfortran -m64 -w -O3 -o <exec> <files>
gfortran -O3 -w -fopenmp -fmax-stack-var-size=32768 -o <exec> <files>
```
This is possibly due to the `if`-statement checking for `"5"` rather than `5`, but that is speculation from my side.
If a compiler is already set, it is not possible to do this using `PMFortranConfig(reconfig = TRUE)`, rather it must be manually changed in `FortConfig.txt`.

```
PMetrics 1.9.7
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.5
```

**Comment by Siel** [comment]
Hi @mhovd My name is Julian and I'll try to help you solve this issue, right now given the new automatic dependency installation process gfortran is fixed as the compiler for the fortran source code. Can I now which compiler/flags are you trying to use? maybe we can flex a little bit this option to let you use the configuration that you need.

I'll be waiting for your comments, Thanks!

**Comment by mhovd** [comment]
Thanks, Julian!
I'm attempting to set the following compiler flags:
```
gfortran -m64 -w -O3 -o <exec> <files>
gfortran -mcmodel=medium -m64 -w -O3 -o <exec> <files>
```
I am unable to do so using `PMFortranConfig(reconfig = TRUE)`, and instead have to do this by manually editing `FortConfig.txt`. Does `PMBuild()` read from this file each time, or are there any hardcoded compiler flags?

**Comment by Siel** [comment]
Right now, the 'master' branch of pmetrics is harcoded to use the following compiler flags:
`
gfortran -m64 -w -O3 -o <exec> <files>
`
`
gfortran -O3 -w -fopenmp -fmax-stack-var-size=32768 -o <exec> <files>
`
Those flags have been fixed for some time because we've been working on an smoother user experience around gfortran for not experienced users. Do the default flags work for you? would you as an user prefer to have a way to personalize those flags?

Thanks!

**Comment by mhovd** [comment]
The default flags work, in the sense that I can run models without issue, and they work as expected.
However, in an effort to attempt to overcome the 2GB size limitation I would like to experiment with different compiler flags, such as the one I mentioned above.

Through support from UNINETT/Sigma2, we were able to overcome this limitation on a HPC-system, although there was a lot of tinkering involved. Here is the [repository ](https://github.com/Sabryr/Pmetrics_test)containing the changes.
It would be ideal to overcome this issue on our workstations as well, as our models/data cause gfortran to hit the 2GB ceiling, making them unable to run.

**Comment by Siel** [comment]
Ok, I'm going to start working on this.

**Comment by CRquantum** [comment]
> 
> 
> The default flags work, in the sense that I can run models without issue, and they work as expected.
> However, in an effort to attempt to overcome the 2GB size limitation I would like to experiment with different compiler flags, such as the one I mentioned above.
> 
> Through support from UNINETT/Sigma2, we were able to overcome this limitation on a HPC-system, although there was a lot of tinkering involved. Here is the [repository ](https://github.com/Sabryr/Pmetrics_test)containing the changes.
> It would be ideal to overcome this issue on our workstations as well, as our models/data cause gfortran to hit the 2GB ceiling, making them unable to run.

Perhaps can add
/LARGEADDRESSAWARE 
or
--enable-large-address-aware 
whichever is correct to the flag for gfortran, in order to overcome the 2GB limit.

**Comment by mnneely** [comment]
The code wasn't working, but I have fixed it.
