### ISSUE TITLE
Namespace is incomplete

### ISSUE THREAD

**Issue by mhovd** [LAPKB/Pmetrics#187]
New users downloading the latest of version of Pmetrics will encounter the following error when running PM_load()` for the first time

```
Use PM_load() to load them.

The following objects have been saved:

NPdata: All output from NPAG
[Some lines omitted for brevity]
Generating report based on the plotly template...

Quitting from lines 8-11 [unnamed-chunk-28] (plotly.Rmd)

Quitting from lines 8-11 (plotly.Rmd)
Error in `loadNamespace()`:
! there is no package called 'DT'
```

We need to make sure that all packages used in the report templates are declared in the `NAMESPACE`, so all dependencies are installed accordingly.

**Comment by Siel** [comment]
I think I updated the namespace while working on the NPcore branch. It
should get fixed when merged

Enviado con Gmail para iPhone

**Comment by mhovd** [comment]
The `ggplot` template uses

- [ ] `ggpubr`
- [ ] `patchwork`
- [ ] `DT`
- [ ] `htmltools`
- [ ] `knitr`

**Comment by mhovd** [comment]
> I think I updated the namespace while working on the NPcore branch. It should get fixed when merged 

Thank you, we should remember this issue for future reports, making sure we declare any imports.
Did you fix it for both templates?

**Comment by Siel** [comment]
Don't think so, as I was just fixing the ones that were popping for me when
I was trying to run the rust template.
*__________________________*
Electronic Engineer
PhD in Electronic Engineering and Computer Sciences.
Researcher at LAPKB - CHLA/USC

**Comment by mhovd** [comment]
Because its a breaking bug for new users, especially on new systems without the packages installed, I made a PR #188 which fixes the changes. Tested on a fresh R install.
