### ISSUE TITLE
Dose data entry at steady state

### ISSUE THREAD

**Issue by sumithmathew9** [LAPKB/Pmetrics#192]
### Discussed in https://github.com/LAPKB/Pmetrics/discussions/191

<div type='discussions-op-text'>

<sup>Originally posted by **VishnuEriyat** January 10, 2024</sup>
I was trying to construct a model for oral rifampicin in adults with pulmonary tuberculosis. There are patients with observation at multiple visits (1 month, 2 month, 5 months etc). When I enter the dose at the in between visits say at 2 months should I put it as EVID 4 and should the ADDL be also set to the number of doses between the last and current visit.</div>

Thank you for the answer, Dr. Michael. How does adding an EVID = 4 affect model building using NPAG algorithm? Will it help NPAG determine the intra-individual variation in PK parameters over the analysis period? If the individual's PK parameter changes over this time frame, how will that affect the estimation of support point and its probability? Will a totally new support point be created for this new EVID = 4? Rifampicin has auto-induction and therefore the rate of elimination changes especially in the first month. How does adding few patients with multiple visits affect model building process using NPAG in such a case?

**Comment by mhovd** [comment]
Like @mnneely writes in his answer, `EVID = 4` will reset the compartments. However, NPAG will still treat it as one patient. As such, there is no inter-occasion / intra-individual effects. An alternative would be to instead use "pseudo-individuals", e.g. use a different ID for each occasion. Then you can manually review the differences in parameters. You can also do this using a covariate with the occasion, but that tends to be messier in my opinion.

**Comment by mhovd** [comment]
Closing this issue for now. In the future, please feel free to post your question on our Discussions page as well
https://github.com/LAPKB/Pmetrics/discussions
