### ISSUE TITLE
Issue with PMbuild()

### ISSUE THREAD

**Issue by jbwoillard** [LAPKB/Pmetrics#20]
Dear Michael I try to update Pmetrics following the procedure described in the lapk website, I had to re-install Rtools40 but I have an error message when I am doing PMbuild()
```
PMbuild()
```
'Pmetrics cannot find required compiled binary files.
Informationÿ: impossible de trouver des fichiers pour le(s) modŠle(s) sp‚cifi‚(s).
Pmetrics cannot detect gfortran and will attempt to download and install all components.
Do you agree? (Y/N)Y
chec du traitement de -File ®ÿC:/Programÿ¯ car le fichier ne comporte pas d'extension ®ÿ.ps1ÿ¯. Sp‚cifiez un nom de fichier de script Windows PowerShell valide, puis r‚essayez.
Windows PowerShell 
Copyright (C) Microsoft Corporation. Tous droits r‚serv‚s.

**Comment by Siel** [comment]
Hi @jbwoillard, it seems that it's a problem with the language since it can't find the .ps1 script file, are you using R studio? Can I have an screenshot of the input?

Thanks!

**Comment by jbwoillard** [comment]
Thanks, yes I am using the last version of Rstudio1.3.959.
Here is the screenshot, it seems that there are french characters not recognized

![image](https://user-images.githubusercontent.com/63699950/86888688-e3893b00-c0fa-11ea-9176-2e69e5fac380.png)

**Comment by Siel** [comment]
@jbwoillard yes, It's something with the language, could you try to execute this after loading pmetrics?

`system2("C:/Windows/System32/WindowsPowerShell/v1.0/powershell", args = c("-ExecutionPolicy","ByPass","-file", paste(system.file("", package = "Pmetrics"), "win/exec.ps1", sep = "/")), wait = T)`

This script should install gfortran for you. 

Also, are you behind some kind of firewall? I just noticed that you got an error with curl, at that step Pmetrics is trying to download [Chocolatey](https://github.com/chocolatey/choco) in order to get Gfortran.

**Comment by jbwoillard** [comment]
I still have a different issue on another computer when trying to install Pmetrics. Gfortran seems to have been installed successfully but when I press to continue, I had an error.
Please find below the screenshot
![image](https://user-images.githubusercontent.com/63699950/87783246-61082600-c834-11ea-8756-91bdad8a45c2.png)

**Comment by Siel** [comment]
Hi @jbwoillard, try re-opening Rstudio, that's usually the issue.

**Comment by vlebreton** [comment]
Hello,

I have same problem of gfortran like @jbwoillard 
![PMbuild](https://user-images.githubusercontent.com/73525546/97282665-3c621800-183f-11eb-9829-566e7719e767.png)
 when I try to install new version of Pmetrics.
I have already install Rtools, and I also install gcc and follow step 5 and Pmetrics manual but there is always same error message,

Can you help me please.

**Comment by Siel** [comment]
@vlebreton do you still have this problem?

**Comment by jbwoillard** [comment]
Dear Julian, I try the new version of Pmetrics but in my Hospital computer,I still have the same issue

`PMbuild()`
Pmetrics cannot find required compiled binary files.
C:\ProgramData\chocolatey\bin\gfortran.exe
C:\rtools40\mingw64\bin\gfortran.exe
C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\gfortran.exe
Pmetrics has detected gfortran and will compile required binary files.
Pmetrics has anonymously registered your installation of this version.
LAPKB does not collect or store any personal or identifying information.If the registration time outs, please run PMbuild(skipRegistration=T) Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to 50.18.143.118 port 4000: Connection refused
Called from: curl::curl_fetch_memory(url, handle = handle)

**Comment by Siel** [comment]
Hi JB,

Please download the latest version of Pmetrics (there is a new one 😊) and
use PMbuild(skipRegistration=T).

Please let me know how it goes.

Julian

**Comment by jbwoillard** [comment]
Oups I read too fast and forgot the new argument! Fantastic everything is ok now. 
Thanks++
jb
