### ISSUE TITLE
Errors in Pmetrics output

### ISSUE THREAD

**Issue by sumithmathew9** [LAPKB/Pmetrics#200]
The new version of Pmetrics is a big leap forward. Thank you team for the excellent work. 
I have noted few mistakes in Pmetrics output files. 

1. Extra 'm' for summaries 

<img width="1100" alt="Error in html file" src="https://github.com/LAPKB/Pmetrics/assets/62738994/b127360d-ae90-4266-849c-2a2e4c2072cc">

2. Bivariate plot (exRes$final$plot(Ke ~ V,
                 marker = list(color = "red", symbol = "diamond"),
                 line = list(color = "purple", dash = "dash", width = 2)
)
Instead of V~Ke~Probability, it is plotting V~Probability~Probability. Wrong legend.
![newplot2](https://github.com/LAPKB/Pmetrics/assets/62738994/fa509752-d0fc-4946-8fc7-06fc1a45f8b9)

**Comment by mhovd** [comment]
Thank you for raising this issue, we will take a look at it!
