### ISSUE TITLE
macosx_version_min has been renamed to -macos_version_min

### ISSUE THREAD

**Issue by sumithmathew9** [LAPKB/Pmetrics#210]
When I trying to run an ITrun or NPrun, it's returning the following error. It looks like Fortran is not working. I am using MacBook system with macOS Sonoma Version 14.2.1. Could you please help?

-macosx_version_min has been renamed to -macos_version_min
ld: malformed mach-o missing relocations, LC_DYLD_INFO, or LC_DYLD_CHAINED_FIXUPS in '/usr/local/Cellar/gcc/9.3.0/lib/gcc/9/libgcc_ext.10.5.dylib'
collect2: error: ld returned 1 exit status
sh: ./it_prep: No such file or directory
gfortran: error: it2bdriv.f: No such file or directory
sh: ./it_run: No such file or directory
Error in if (success) { : missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In system(paste("./", prepFileName, " MacOSX < PMcontrol", sep = "")) :
  error in running command
2: In system(paste("./", runFileName, " < go", sep = "")) :
  error in running command

**Comment by sumithmathew9** [comment]
I have sorted out this issue. I have updated R and all packages to most recent version and then removed and reinstalled both 'remotes' and 'Pmetrics', packages. Now it's working fine.

**Comment by mhovd** [comment]
In case this error pops up in the future, do you have any idea what triggered it?
Did you have Pmetrics installed previously, and performed an OS upgrade? Was it an update for xcode?

**Comment by sumithmathew9** [comment]
I recently downloaded Xcode and this was preventing installation of Pmetrics. Therefore, I had to remove Xcode to allow the Apple's own system to help with Pmetrics installation.
