### ISSUE TITLE
Can't install Pmetrics package

### ISSUE THREAD

**Issue by Oalkilani** [LAPKB/Pmetrics#239]
I am new to Pmetrics, but when I try to install the Pmetrics package, I receive this message: 
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/salma/AppData/Local/Temp/RtmpaIkrwB/file1d1c188f4ebf/Pmetrics_2.1.1.tar.gz’ had non-zero exit status

Any idea? @mnneely 
I really appreciate any help you can provide.

**Comment by mnneely** [comment]
Can you try reinstalling now? I updated package Namespace.

**Comment by Oalkilani** [comment]
Thank you so much! It is working.

**Comment by mnneely** [comment]
Great!
