### ISSUE TITLE
OS not passed to .installOrUpdateGCC

### ISSUE THREAD

**Issue by mhovd** [LAPKB/Pmetrics#24]
This issue was discovered by a student attempting to install Pmetrics for the first time on a Mac.

Upon running `PMbuild()` this error came up

```r
Error in .installOrUpdateGCC()
    argument "OS" is missing, with no default
```

A quickfix to this was to edit the function with trace, in order to successfully run PMbuild()
`trace(Pmetrics:::.installOrUpdateGCC(),edit = TRUE)`
and manually forcing `OS = 1`.

**Comment by Siel** [comment]
Thank you for your report, It was just fixed in the latest commit.
