### ISSUE TITLE
Pmetrics installation - data issues

### ISSUE THREAD

**Issue by mnneely** [LAPKB/Pmetrics#242]
### Discussed in https://github.com/LAPKB/Pmetrics/discussions/240

<div type='discussions-op-text'>

<sup>Originally posted by **BoburaII** November  9, 2024</sup>
Hello, 
I've updated MacOS and run into trouble with Pmetrics. Attempts to re-install have been unsuccessful, with the following error message: 

* installing *source* package ‘Pmetrics’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘ITex’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘ITex’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘NPex’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘NPex’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘NPex_val’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘NPex_val’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘badData’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘badData’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘dataEx’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘dataEx’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘modEx’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘modEx’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘modelLibrary’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘modelLibrary’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘simEx’
Warning: namespace ‘Pmetrics’ is not available and has been replaced
by .GlobalEnv when processing object ‘simEx’
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘Pmetrics’ in library.dynam(lib, package, package.lib):
 shared object ‘Pmetrics.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Pmetrics’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/5z/2ms25s0d3nj5thkpd0bvlqk40000gn/T//RtmpcSB12m/file12754f1ea749/Pmetrics_2.1.1.tar.gz’ had non-zero exit status

I seem not to figure out the error. Would appreciate help with a work around.
Thanks
</div>

**Comment by mnneely** [comment]
I rebuilt the package NAMESPACE and that seems to have fixed the problem. Please try installing again. Mark this post as a solution if it works so that we can close the issue.

**Comment by ChrisKonig** [comment]
It worked for me. Installation complete. Thanks for the super fast resolution on this. :)

**Comment by mnneely** [comment]
Excellent! I'll mark this closed then. Thanks for letting me know.

**Comment by BoburaII** [comment]
Hi @mnneely, thanks for the quick rebuild of the Namespace package, it sorted the previous issue. However, running PMbuild() to complete the installation fails to compile D0prep on a mac(Sequoia 15.1), error details below. Again, thanks for your help, always!

Compiling 1 of 9: NPprep...
Compiling 2 of 9: NPeng...
Compiling 3 of 9: ITprep...
Compiling 4 of 9: ITeng...
Compiling 5 of 9: ITerr...
Compiling 6 of 9: SIMeng...
**Compiling 7 of 9: DOprep...-macosx_version_min has been renamed to -macos_version_min**
ld: library 'System' not found
collect2: error: ld returned 1 exit status
Error in PMbuild() : 
There was an error compiling DOprep.

**Comment by mnneely** [comment]
This sounds like a Fortran issue on your machine, as I am also running Sequoia and could not reproduce the error.  I have the homebrew GCC version of gfortran 14.2.0 running, which is [current](https://formulae.brew.sh/formula/gcc). It sits in `/opt/homebrew/bin/gfortran`, which is in my path, retrieved with `echo $PATH` from the terminal.

**Comment by BoburaII** [comment]
I've updated Fortran to version 14.2.0. Installation complete :). Many thanks for the help.

**Comment by alee8868** [comment]
Hi @mnneely , I have hit this exact same issue, I also just updated to Sequoia and have the most recent gfortran 14.2 - Intel sequoia installed (and re-installed a few times). When running PMbuild() to complete installation I also fail to compile DOprep on MacOS.
This is the output:

> PMbuild()
Pmetrics cannot find required compiled binary files.
Pmetrics has detected gfortran and will compile required binary files.
If the registration time outs, please re-run PMbuild(skipRegistration = TRUE) Pmetrics has anonymously registered your installation of this version.
LAPKB does not collect or store any personal or identifying information.

Compiling 1 of 9: NPprep...
Compiling 2 of 9: NPeng...
Compiling 3 of 9: ITprep...
Compiling 4 of 9: ITeng...
Compiling 5 of 9: ITerr...
Compiling 6 of 9: SIMeng...
Compiling 7 of 9: DOprep...ld: library 'System' not found
collect2: error: ld returned 1 exit status
Error in PMbuild() : 
There was an error compiling DOprep.
Did you select the right fortran compiler?  If yes, try reinstalling fortran.
For gfortran, log into www.lapk.org and access system-specific tips on the Pmetrics installation page (step 5).

Do you know how to move forward on this one?
Thanks!

**Comment by mnneely** [comment]
Seems like either your gfortran path is wrong or it hasn’t fully installed. This is why we are moving to Rust - Fortran is so old it is a pain in the neck. Are you installing with homebrew? What do you get with `which gfortran` in the Terminal? Alternatively, what is in `echo $PATH`?

**Comment by alee8868** [comment]
I installed gfortran through github (https://github.com/fxcoudert/gfortran-for-macOS/releases)
when I write 'which gfortran' I get '/usr/local/bin/gfortran'
when I write echo $PATH I get this
adamlee@MacBook-Air-5 ~ % echo $PATH
/usr/local/bin:/usr/local/sbin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin

I am quite new to all this so if I am writing things incorrectly in Terminal, that may also be why I can't figure this out

I did install homebrew but I did not know I could install gfortran through homebrew.

**Comment by mnneely** [comment]
I'd try installing through [homebrew](https://formulae.brew.sh/formula/gcc).

**Comment by alee8868** [comment]
Got it to work. Thank you so much!

**Comment by mnneely** [comment]
Excellent. Frustrating how fussy Fortran is.
