### ISSUE TITLE
SIMparse - Error in parsing large or very small numbers

### ISSUE THREAD

**Issue by Siel** [LAPKB/Pmetrics#25]
if the simulation contains number larget than x.yzE+100 or lower than x.yzE-100, the simulator is going to write those numbers using a wrong format that removes the E character.

I.E:
![image](https://user-images.githubusercontent.com/1023006/93512777-aea71a80-f8d9-11ea-9ff0-35bfaf854e2f.png)

This makes SIMparse to crash:

> data_cro <- SIMparse('simout1.txt')

Processing 1 simulated data file(s)
0% Error in scan(allfiles[n], skip = amtlines[a], n = nsim * (nobs + 1),  : 
  scan() expected 'a real', got '0.6797844+100'

**Comment by Siel** [comment]
Putting all the E(s) manually solves the problem. I think the problem might be related to the format we're using in fortran to write that file.

**Comment by mnneely** [comment]
This problem is typically avoided by using the limits argument to SIMrun, e.g.

```SIMrun(...,limits = c(0,3))```

This avoids simulating physiologically impossible parameters.
