### ISSUE TITLE
NA error

### ISSUE THREAD

**Issue by mshaer-pkpd** [LAPKB/Pmetrics#26]
When I run the PMload, "errfile.run#" with character (empty) value is generated and I get this error when I try to run makeValid():

`Error in do_one(nmeth) : NA/NaN/Inf in foreign function call (arg 1)
In addition: Warning message:
In storage.mode(x) <- "double" : NAs introduced by coercion`

SIMrun won't run too.

Thanks
Mo

**Comment by mshaer-pkpd** [comment]
Sorry forgot to add SIMrun error:
`Error in sdVector[i] * sdVector[j] : 
  non-numeric argument to binary operator`

Thanks again!

**Comment by Siel** [comment]
Is it possible to have the files you’re using to try to reproduce the error on my end?

Thanks!

**Comment by mshaer-pkpd** [comment]
Sure. Please find attached.

Thanks
Mo


[cid:54c77d06-4dae-4cd6-bb91-f35afc0fa826@namprd22.prod.outlook.com]

Mohammad H. Alshaer, Pharm.D., Ph.D., BCPS
Research Assistant Professor
Infectious Disease Pharmacokinetics Laboratory
Department of Pharmacotherapy & Translational Research | College of Pharmacy, and
Emerging Pathogens Institute
University of Florida
1600 SW Archer Rd | Medical Science Building | Room P4-05 | PO Box 100486
Gainesville, FL 32610
Tel: 352-273-6803
Fax: 352-273-6804
Email: mshaer@ufl.edu<mailto:mshaer@ufl.edu>
______________________________________________________________________


[cid:31cfb4ef-eee6-4c42-89b7-e21d2f82e9af@namprd22.prod.outlook.com]

[cid:1b8c948d-9784-4b8c-a130-69ef550ee3f5@namprd22.prod.outlook.com]

On Nov 25, 2020, at 10:08 AM, Julian Otalvaro <notifications@github.com<mailto:notifications@github.com>> wrote:

[External Email]


Is it possible to have the files you’re using to try to reproduce the error on my end?

Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LAPKB_Pmetrics_issues_26-23issuecomment-2D733763462&d=DwMFaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=a0brpgYnNXpZDP1jA5rcPQ&m=8dS3BVBwaFY3-bkBp1Cn8RMZ28aUtLe1HVKtfvXlIOM&s=gvOFf7UheqLVlYiUK5Sg12KrICxcRBDUEm4bLP5IznQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AP7GEDZSWBGDUABB7WE6IITSRUMWBANCNFSM4S2EQEJA&d=DwMFaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=a0brpgYnNXpZDP1jA5rcPQ&m=8dS3BVBwaFY3-bkBp1Cn8RMZ28aUtLe1HVKtfvXlIOM&s=WmIj7Jyl8_h9y86lChcemUBwR2O8vYRTzC7hq1YPQu4&e=>.


#Pri

Ka, 0, 5
Tlag1, 0, 1

V0, 40, 100
CL, 0, 15




#Cov
Weight
Female
Age
CLcr
HIV
Scr
CGcr

#Lag
TLAG(1) = Tlag1

#Sec
V = V0 * Weight/55
Ke = CL*(CGcr/115)/V


#Out

Y(1) = X(2)/V



#Err

G=2

0.1,0.1,0,0

**Comment by Siel** [comment]
The error model is not going to be enough to reproduce the error, can I have the compressed version of the folder you're trying to load?

**Comment by mshaer-pkpd** [comment]
Sent it to your personal email as it failed to attach here.

**Comment by Siel** [comment]
I got it, thanks! I'm going to work on that :)

**Comment by Siel** [comment]
I was finally able to reproduce your error. The error happens in the elbow plot. Can you send me your data file?

**Comment by mshaer-pkpd** [comment]
Looks like I cannot attach files here. I sent it separately to your email. If you can check the SIMrun too, that will be excellent!

Many thanks!
Mo

On Dec 4, 2020, at 4:05 PM, Julian Otalvaro <notifications@github.com> wrote:

﻿
[External Email]

I was finally able to reproduce your error. The error happens in the elbow plot. Can you send me your data file?

**Comment by Siel** [comment]
I'll need the model you're using to simulate too. 😄

**Comment by mshaer-pkpd** [comment]
I attached the model file to the previous email. Please let me know if you need any more files. Thanks

On Dec 4, 2020, at 4:19 PM, Julian Otalvaro <notifications@github.com> wrote:

﻿
[External Email]

I'll need the model you're using to simulate too. 😄

**Comment by Siel** [comment]
@masyamada and I found the error, it seems that in order to use makeValid you cannot use string ids. as a workaround, if you transform all your ids to numeric incremental numbers. it should work.

In the meantime we're going to try to prevent this error to happen.

**Comment by mshaer-pkpd** [comment]
makeValid worked but not SIMrun. Got the error I mentioned in my second comment above

**Comment by Siel** [comment]
The SIMRun issue was addressed in #34.

**Comment by Siel** [comment]
Problem solved
