### ISSUE TITLE
Cannot create PMpost object

### ISSUE THREAD

**Issue by jjliupharmd** [LAPKB/Pmetrics#28]
Hi there,

I am encountering an error as the NP run converges and finishing up - the post.x object cannot be successfully created (see screenshot below).

And when I load the run folder [PMload(x)] and try to use makePost(x) argument to create a post.x object with NPdata.x, I received the following message.  It seems that some values were either zero or _NA_ in the final NPdata that has led to this error?

![2](https://user-images.githubusercontent.com/65783440/97126904-8ac3c980-170e-11eb-9245-f26dbf2b3a7a.png)
![1](https://user-images.githubusercontent.com/65783440/97126906-8ac3c980-170e-11eb-8faa-b44f7e2deec4.png)

Pls advise on how I can fix this one.  Currently on R 3.6.3 and Pmetrics 1.9.7.

Thanks!

**Comment by Siel** [comment]
Hi, sorry for the late response, are you still having this problem? Can I have the data you are using to reproduce the error on my end? thanks

**Comment by jjliupharmd** [comment]
No prob - thanks for taking the time!

Could you provide an email to which I can send the dataset?  Thanks!

JJ

- sent from my Pixel

**Comment by Siel** [comment]
Yes, my email is juliandavid347@gmail.com
