### ISSUE TITLE
Error in Pmetrics Report label

### ISSUE THREAD

**Issue by Trepon** [LAPKB/Pmetrics#30]
In the html reports, when viewing plots, there are 2 different plots labelled as "Normalized Mean". I guess one of them should be "Normalized Median".

![image](https://user-images.githubusercontent.com/58770987/100206581-d385c280-2f06-11eb-97b6-588e88c57099.png)

**Comment by Siel** [comment]
Thank you for reporting this error, I was updating the graphs and missed that, would be fixed in the next minor patch.
