### ISSUE TITLE
When input = 2 and dose duration different than 0, the dose event seems to be ignored

### ISSUE THREAD

**Issue by Trepon** [LAPKB/Pmetrics#31]
Hello,
I have a problem with doses for a model with an absorption compartment (1) and a central compartment (2), and two routes of administration (input = 1 for compartment 1, input = 2 for compartment 2). When a dose is administered in the central compartment (2), i.e. an IV infusion with duration = 1, the dose event seems to get ignored by Pmetrics. However, when setting it to an IV bolus (duration = 0) it seems to work correctly.
See below for examples (all files are attached). I am using an example dataset with 1 patient. The line at TIME = 120 is the one we will focus on (INPUT = 2).
Thank you for your help.

[examples.zip](https://github.com/LAPKB/Pmetrics/files/5597806/examples.zip)

**Example model**
`#Primary
Ka, 0.1, 0.9
Ke, 0.001, 0.1
V, 30, 120
Tlag1, 0, 4

#Cov
WT
AFRICA
AGE
GENDER
HEIGHT

#Lag 
TLAG(1) = Tlag1

#Out
Y(1) = X(2)/V

#Err
G=5
0.02, 0.05, -0.0002, 0`

**Example 1** at TIME = 120, DURATION = 0 and INPUT = 2.

POPDATA DEC_11 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
#ID | EVID | TIME | DUR | DOSE | ADDL | II | INPUT | OUT | OUTEQ | C0 | C1 | C2 | C3 | WT | AFRICA | AGE | GENDER | HEIGHT
1 | 1 | 0 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 24 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 48 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 72 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 96 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 120 | . | . | . | . | . | 10.44 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 120 | 0 | 600 | . | . | 2 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 121 | . | . | . | . | . | 12.89 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 122 | . | . | . | . | . | 14.98 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 125.99 | . | . | . | . | . | 16.69 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 129 | . | . | . | . | . | 20.15 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 132 | . | . | . | . | . | 14.97 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 143.98 | . | . | . | . | . | 12.57 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160

![example1](https://user-images.githubusercontent.com/58770987/100250028-7fe29b80-2f3d-11eb-96d7-abc158a742e0.png)
Here, everything is working as intended, the dose at TIME = 120 is correctly simulated.

**Example 2** at TIME = 120, DURATION = 1 and INPUT = 2

POPDATA DEC_11 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
#ID | EVID | TIME | DUR | DOSE | ADDL | II | INPUT | OUT | OUTEQ | C0 | C1 | C2 | C3 | WT | AFRICA | AGE | GENDER | HEIGHT
1 | 1 | 0 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 24 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 48 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 72 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 96 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 120 | . | . | . | . | . | 10.44 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 120 | 1 | 600 | . | . | 2 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 121 | . | . | . | . | . | 12.89 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 122 | . | . | . | . | . | 14.98 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 125.99 | . | . | . | . | . | 16.69 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 129 | . | . | . | . | . | 20.15 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 132 | . | . | . | . | . | 14.97 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 143.98 | . | . | . | . | . | 12.57 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160

![example2](https://user-images.githubusercontent.com/58770987/100251158-bbca3080-2f3e-11eb-8ef0-81ea53f0e7a6.png)
Here, the dose event at TIME = 120 seems to be ignored.

**Example 3** at TIME = 120, DURATION = 1 and INPUT = 1

POPDATA DEC_11 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
#ID | EVID | TIME | DUR | DOSE | ADDL | II | INPUT | OUT | OUTEQ | C0 | C1 | C2 | C3 | WT | AFRICA | AGE | GENDER | HEIGHT
1 | 1 | 0 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 24 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 48 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 72 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 96 | 0 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 120 | . | . | . | . | . | 10.44 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 1 | 120 | 1 | 600 | . | . | 1 | . | . | . | . | . | . | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 121 | . | . | . | . | . | 12.89 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 122 | . | . | . | . | . | 14.98 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 125.99 | . | . | . | . | . | 16.69 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 129 | . | . | . | . | . | 20.15 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 132 | . | . | . | . | . | 14.97 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160
1 | 0 | 143.98 | . | . | . | . | . | 12.57 | 1 | 0.02 | 0.0506 | -0.0002 | 0 | 46.7 | 1 | 21 | 1 | 160

![example3](https://user-images.githubusercontent.com/58770987/100251680-5165c000-2f3f-11eb-8eab-0dbaf4b90648.png)
When changing the input number to compartment 1, it seems to work correctly.

**Comment by Trepon** [comment]
Hi, any update on this issue? We're kind of stuck on this :-)
Thank you for your help
RB

**Comment by mhovd** [comment]
`INPUT` in your data file does not relate to the compartment where the drug is administered, but is used to separate different drugs. If you are using a model with differential equations, use `RATEIV(n)` for your `n`th drug bolus injection / infusion.

If you want to change the compartment where drugs are delivered, use
```
#BOL
NBCOMP(n) = x
```
Which tells PMetrics to administer your `n`th drug to compartment `x`

**Comment by Trepon** [comment]
Thank you for your reply, that clarifies a lot!

So, if I understood correctly, when I want to develop a model for 1 drug with 2 routes of administration (oral and IV infusion), `INPUT` should be set to 1. When `DUR = 0` in the dataset, the dose is interpreted as a bolus and delivered in the 1st (oral) compartment, and when `DUR > 0` it is interpreted as an infusion and delivered into the 2nd (central) compartment.
It seems like example 3 above was the correct way to do it.
