### ISSUE TITLE
'gfortran' not found

### ISSUE THREAD

**Issue by ivette-herrera** [LAPKB/Pmetrics#40]
Hi!
 I have an error message when I run PMbuild()

**Pmetrics has installed gfortran and will now compile required binary files.
Pmetrics has anonymously registered your installation of this version.
LAPKB does not collect or store any personal or identifying information.If the registration time outs, please run PMbuild(skipRegistration=T) 
Compiling 1 of 9: NPprep...Error in system(serialCommand, intern = T, ignore.stderr = F) : 
  'gfortran' not found**

I have tried to install it manually but the program cannot find it.

**Comment by Siel** [comment]
I've seen this error before in windows. Try re-opening Rstudio after the fortran instalation. It might fix the problem.

Try that and let me know hot it goes.

**Comment by ivette-herrera** [comment]
I tried, but the problem continues

**Comment by Siel** [comment]
In that case you might want to try to install gfortran manually: https://w3.cs.jmu.edu/bernstdh/web/common/help/fortran-setup.php, this is a tutorial I found. But you can use another method to get gfortran in your computer.

**Comment by CRquantum** [comment]
it is a gfortran problem, please see here, https://github.com/LAPKB/Pmetrics/issues/44#issuecomment-797282955
let us know if the problem is solved or not.

**Comment by harishkaushikbugworks** [comment]
Can any one post detailed video on how to fix this issue, even i am also facing similar issue

**Comment by Siel** [comment]
Hi @harishkaushikbugworks, please refer to: http://www.lapk.org/Pmetrics_install_manual.php step 4. That is our tutorial to install gfortran if the automatic installation fails. Please let us know if you are still having issues after that.

**Comment by suzloup** [comment]
Hi @Siel and @mnneely! We have manually installed gfortran on a Windows10 laptop and PMtest() says it has installed successfully - but when we run we receive an error: np_prep.exe - system error: The code execution cannot proceed because libgfortran-5.dll was not found. Reinstalling the program may fix this problem. Is this a problem with our version of gfortran perhaps? Best wishes, Suzie

**Comment by Siel** [comment]
Suzie, Sorry for the late response, usually that error means a problem with your gfortran binary. I'd recommend you to install the minGW package. that Gfortran works fine on windows.  I'm closing this issue for the time being, feel free to reopen if your problem persists.
