### ISSUE TITLE
There was an error compiling NPprep.

### ISSUE THREAD

**Issue by elbaromero** [LAPKB/Pmetrics#41]
Hola Julian,
I have carried out those steps specified on the web page of the Pmetrics site to install the software. I had a version of g95 Fortran compiler for use with NONMEM. After installing the devtools, Rtools and performing the PMcheck (), the systems detected gfortran and start compilations, the following message appears on my screen:

_Compiling 1 of 9: NPprep...Error in PMbuild() : 
There was an error compiling NPprep.
Did you select the right fortran compiler?  If yes, try reinstalling fortran.
For gfortran, log into www.lapk.org and access system-specific tips on the Pmetrics installation page (step 5)._

I check for more information at Pmetrics website, that redirects me to [older instruccions](http://www.lapk.org/Pmetrics_install_manual.php). It seems if I have another Fortran installation on my system, there is an extra steps I should perform. I look forward to your support.
Thank you!

**Comment by Siel** [comment]
Hi @elbaromero, the current Pmetrics installation is not supporting other compiler than gfortran, this might be fixed in the future #18. Please try again with gfortran. re-opening Rstudio before trying again.

**Comment by CRquantum** [comment]
Please check here, https://github.com/LAPKB/Pmetrics/issues/44#issuecomment-797282955
I have the same problem before, but solved it by the installing stawberry perl, and use the gfortran in it as mentioned above. 
The problem happens because Pmetrics did not find (from the system's environment variable) the correct version of gfortran which it can really use.

**Comment by Siel** [comment]
Hi @elbaromero, I'm going to close this issue, if your problem is still not solved please feel free to reopen it.
