### ISSUE TITLE
error when running SIMrun and SIMparse

### ISSUE THREAD

**Issue by Yuanzhang-d** [LAPKB/Pmetrics#42]
Hi!
I have an error message when I run SIMrun and SIMparse：
my code：“SIMrun(poppar=final.2,data="2501b.csv",model="3C_1.txt",include=1:4,limits=NA,nsim=100,doseNoise=c(0.05,0.1,0.15,0.2))”，I don't know how to change the noise coefficeintes.

result：
PLEASE RERUN THE PROGRAM AND SELECT SMALLER NOISE COEFFICIENTS
 FOR THE DOSAGE AMOUNTS.
 HIT ANY KEY TO CONTINUE: 
At line 8458 of file SIMeng_114.f (unit = 5, file = 'stdin')
Fortran runtime error: End of file

Use, for example, SIMparse(“simout1.txt”) to extract simulator output for analysis or plotting.
Warning messages:
1: In shell("montbig.exe DOS < simControl.txt", invisible = T) :
  'montbig.exe DOS < simControl.txt' execution failed with error code 2
2: In shell("montbig.exe DOS < simControl.txt", invisible = T) :
  'montbig.exe DOS < simControl.txt' execution failed with error code 2
3: In shell("montbig.exe DOS < simControl.txt", invisible = T) :
  'montbig.exe DOS < simControl.txt' execution failed with error code 2
4: In shell("montbig.exe DOS < simControl.txt", invisible = T) :
  'montbig.exe DOS < simControl.txt' execution failed with error code 2

my code：simdata <- SIMparse("simout1.txt")
result：
Processing 1 simulated data file(s)
  |     |   0%Error in scan(allfiles[n], skip = obslines[a], n = nsim * (nobs + 1),  : 
  scan() needs 'a real', not 'THE'
moreover : Warning messages:
1: In processfile(n) : The forced change produces NA
2: In rep(1:nsim, each = nobs) : Only use the first element in the 'each' argument

**Comment by Siel** [comment]
There are multiple ways to modify the noise coefficients, you can modify them here: doseNoise=c(0.05,0.1,0.15,0.2) or inside your model.txt or individually for each measurement in your data file.

**Comment by Siel** [comment]
@Yuanzhang-d I'm going to close the issue supposing that is solved, please feel free to reopen it if that is not the case.
