### ISSUE TITLE
Pmetrics package cannot be loaded without internet access

### ISSUE THREAD

**Issue by Trepon** [LAPKB/Pmetrics#43]
Hi,
When there is no internet access, we get this error message when trying to load Pmetrics:
```
library(Pmetrics)
Error: package or namespace load failed for 'Pmetrics':
 .onAttach failed in attachNamespace() for 'Pmetrics', details:
  call: curl::curl_fetch_memory(url, handle = handle)
  error: Could not resolve host: api.github.com
```
It would be nice to be able to develop some models in a limited connectivity environment :-)

**Comment by mnneely** [comment]
Pmetrics does not depend on an internet connection to work once all components are installed. However, upon loading, it does check our server for updates if there is a connection.  The error you experienced usually occurs when your computer is connected to a wireless network without internet, i.e. you haven’t authenticated on the network. If that is not the case here, let us know as there is some other issue going on.

On Feb 5, 2021, at 6:57 AM, Ronan Bellouard <notifications@github.com> wrote:

﻿

Hi,
When there is no internet access, we get this error message when trying to load Pmetrics:

library(Pmetrics)
Error: package or namespace load failed for 'Pmetrics':
 .onAttach failed in attachNamespace() for 'Pmetrics', details:
  call: curl::curl_fetch_memory(url, handle = handle)
  error: Could not resolve host: api.github.com


It would be nice to be able to develop some models in a limited connectivity environment :-)

**Comment by Trepon** [comment]
Hi, thanks for the reply. Sadly, I still get the error when all networks are turned off (airplane mode and no ethernet network):
![Screenshot 2021-02-12 161401](https://user-images.githubusercontent.com/58770987/107785884-70f5d300-6d4d-11eb-815a-7a2a3b1896d2.png)

**Comment by CRquantum** [comment]
> 
> 
> Hi, thanks for the reply. Sadly, I still get the error when all networks are turned off (airplane mode and no ethernet network):
> ![Screenshot 2021-02-12 161401](https://user-images.githubusercontent.com/58770987/107785884-70f5d300-6d4d-11eb-815a-7a2a3b1896d2.png)

I can be completely wrong, but perhaps you could try the following command before load Pmetrics, 
options(download.file.method = "wininet")
if it does not work then perhaps try another one,
options(download.file.method = "libcurl")

**Comment by Trepon** [comment]
Thank you, I tried but sadly I still get the same error.

**Comment by Siel** [comment]
Hi @Trepon, which version of pmetrics are you using? if you're still having those issues we can have a video call and I could try to help you.

Please let me know

**Comment by mnneely** [comment]
No further comments in over a year. Please reopen the issue if still a problem, but closing this for now.
