### ISSUE TITLE
Feature request: option to disable HTML report opening

### ISSUE THREAD

**Issue by mhovd** [LAPKB/Pmetrics#46]
When using Pmetrics on a headless server, the HTML report opening could cause issues.
As such, it would be nice to have an argument in NPrun to disable the automatic opening of the HTML report, while still performing the standard post-run processing.

`intern = TRUE` is only an option on OS X, and is not a suitable replacement, as the R session will be busy.

Is this something that may be considered?

**Comment by Siel** [comment]
We could create a new flag to include that feature, I would like to hear @mnneely opinion in this regard, I could implement it.

**Comment by mnneely** [comment]
I'm open to that idea. We should implement it. Perhaps add `report` as an argument, with default `report = TRUE`.

**Comment by Siel** [comment]
I'm implementing it now

**Comment by Siel** [comment]
I just added this functionality, it is available on the Version2 branch

**Comment by mhovd** [comment]
Thank you for the work @Siel!

However, currently `report = FALSE` will prevent report _generation_ as well, which is not desired.
Instead, it would be nice if `report = FALSE` prevented only the _opening_ of the report, e.g. only implement
```r
if(report){browseURL(paste(gsub("/", rep, outpath), "/", type, "report.html", sep = ""))}
```

**Comment by Siel** [comment]
Hi @mhovd, I choosed to do it this way because we have the PMreport method to generate the report, I know it is not much but generating the report also takes some time.

What do you think professor @mnneely ?

**Comment by mnneely** [comment]
I think it is reasonable to generate the report and suppress the automatic opening. It can be useful to look at the report later.

**Comment by Siel** [comment]
Ok, I will change it now :)

**Comment by Siel** [comment]
Now the report is going to be generated automatically and the 'report' flag will only controll if its going to be automatically opened or not
