### ISSUE TITLE
When using ifort on unix, correct syntax for syntax-only

### ISSUE THREAD

**Issue by Sabryr** [LAPKB/Pmetrics#6]
According to :
https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference-syntax-only
Linux and macOS:  -syntax-only
Windows: | /syntax-only

In the R file: PMutilities.R
The Windows version is included and this make it fail on Centos6.8
if (length(grep("ifort", fortran) > 0)) { syntaxcheck <- paste(fortran, "/syntax-only", modelFor) }

So I sugest:
 if (length(grep("ifort", fortran) > 0)) {
    if (OS == 1 | OS == 3) {
      syntaxcheck <- paste(fortran, "-fsyntax-only", modelFor)
    } else {
      syntaxcheck <- paste(fortran, "/syntax-only", modelFor)
    }
  }

**Comment by Siel** [comment]
The suggested solution will be released on the next version of Pmetrics, Thanks!
