### ISSUE TITLE
Montecarlo simulation

### ISSUE THREAD

**Issue by harishkaushikbugworks** [LAPKB/Pmetrics#63]
Hello All,

It will be of help, if any one could provide a working example of Montecarlo simulation and PTA analysis

Regards
Harish

**Comment by Siel** [comment]
Hi @harishkaushikbugworks,
There are example of both, montecarlo simulations and PTA analysis on our examples folder @ [http://www.lapk.org/software/Pmetrics/Examples.zip](http://www.lapk.org/software/Pmetrics/Examples.zip).

I'll close this issue
