### ISSUE TITLE
Model error with two outputs

### ISSUE THREAD

**Issue by mnneely** [LAPKB/Pmetrics#68]
Raised by @livPKPD. List model with 2 outputs not being translated correctly, so missing second line of error coefficients.

**Comment by mnneely** [comment]
I believe Version2 branch now fixes this issue. @livPKPD, can you test and let me know if I can close this issue? You'll need to pull the revised branch with install_github("LAPKB/Pmetrics", ref = "Version2")

**Comment by livPKPD** [comment]
Hi, thanks for the advice. Unfortunately, although I installed devtools, then installed and built the revised branch as above, I still et the same error: 

MODEL REPORT:
There are errors in your model file.

There is 1 line of error coefficients in the model file, but 2 output equations.
These must be the same.

**Comment by mnneely** [comment]
Make sure you completely quit Rstudio and restart. Sometimes it does not actually update to a newer library version without this. I tested the new script on your model and it did indeed work on my computer.

**Comment by Siel** [comment]
It does work for me: 

````
#pri
Ka, 0.100000, 7.000000
V, 0.100000, 50.000000
Kcp, 0.010000, 80.000000
Kpc, 0.010000, 50.000000
Kcs, 0.010000, 80.000000
Ksc, 0.010000, 50.000000
Vcns, 0.010000, 60.000000
SCL, 0.010000, 15.000000

#cov
AGE
sex_m0_f1
prevflc
creat
alt
arm
weight
creatmgdl
crcl

#dif
XP(1)=-Ka * X(1)
XP(2)=- (Kcp + Kcs + (SCL/V))X(2) + (KscX(3)) + (KpcX(4)) + (KaX(1))
XP(3)=KcsX(2) - KscX(3)
XP(4)=KcpX(2) - KpcX(4)

#out
Y(1)=X(2)/V
Y(2)=X(3)/Vcns

#err
L=3.000000
0.025000,0.100000,0.000000,0.000000
0.025000,0.100000,0.000000,0.000000
````

But I checked the code and we are printing the second line of coefficients, should we print again the first one instead? I remember we once talked about keeping the first error block as the default for all the others while we implement multiple lambda/gamma models. @mnneely

**Comment by livPKPD** [comment]
Thank you - once I restarted R it ran! Delighted :)

**Comment by mnneely** [comment]
Super. I’ll close this issue.
