### ISSUE TITLE
makeValid not working with outeq>1

### ISSUE THREAD

**Issue by mnneely** [LAPKB/Pmetrics#75]
Reported by @mshaer-pkpd.

**Comment by mnneely** [comment]
Making progress on this. Can create valid object properly, but need to finish correct plotting.

**Comment by mnneely** [comment]
I think I have fixed it. @mshaer-pkpd, can you test it? Note, that this is beta for Pmetrics Version 2, which you will need to install with this command:

`devtools::install_github("LAPKB/Pmetrics", ref = "Version2")`

Then run PMbuild().
Example code to try:

```{r echo=T, eval=F}
run215 <- PM_load(215) #your number may be different

run215$validate(limits = c(0,3)) #this is the simplest code which provides limits, but makes you answer questions 

#don't need to execute this code below if you ran line above
run215$validate(binCov=c('crcl', 'glub'), doseC = 6, timeC = 5, limits=c(0,3)) #adding in answers to bypass questions

run215$save("valid.Rds") #will save the new validation for retrieval later if you wish
run215 <- PM_result$load("valid.Rds") #this is how you retrieve it
run215$valid$plot(type = "npde", log = T, outeq = 1) #try a plot
run215$valid$plot(type = "vpc", log = T, outeq = 1) #or another
```

**Comment by mnneely** [comment]
@mshaer-pkpd confirmed new version to be working. Closing the issue.

**Comment by Johnny0514** [comment]
> I think I have fixed it. [@mshaer-pkpd](https://github.com/mshaer-pkpd), can you test it? Note, that this is beta for Pmetrics Version 2, which you will need to install with this command:
> 
> `devtools::install_github("LAPKB/Pmetrics", ref = "Version2")`
> 
> Then run PMbuild(). Example code to try:
> 
> ```
> run215 <- PM_load(215) #your number may be different
> 
> run215$validate(limits = c(0,3)) #this is the simplest code which provides limits, but makes you answer questions 
> 
> #don't need to execute this code below if you ran line above
> run215$validate(binCov=c('crcl', 'glub'), doseC = 6, timeC = 5, limits=c(0,3)) #adding in answers to bypass questions
> 
> run215$save("valid.Rds") #will save the new validation for retrieval later if you wish
> run215 <- PM_result$load("valid.Rds") #this is how you retrieve it
> run215$valid$plot(type = "npde", log = T, outeq = 1) #try a plot
> run215$valid$plot(type = "vpc", log = T, outeq = 1) #or another
> ```
Dear Professor Neely:
   I have tried the commands, but the "valid.Rds" file seemed to be empty. The commands below can not be executed successfully. I do not know what to do next.
"run215 <- PM_result$load("valid.Rds") #this is how you retrieve it
> run215$valid$plot(type = "npde", log = T, outeq = 1) #try a plot
> run215$valid$plot(type = "vpc", log = T, outeq = 1) #or another"
   Look forward to your reply!
   Kind Regards!
