### ISSUE TITLE
Error creating PMfinal and PMcycle

### ISSUE THREAD

**Issue by richwilson17** [LAPKB/Pmetrics#91]
Hi there,

I am running Pmetrics on an M1 Mac. The install was fine and PMtest ok. I am able to execute an NPAG and OP objects are created, but the process runs into problems at the end creating cycle and final objects. I have copied the error below. 

The same run works fine on an Intel Mac and creates all objects appropriately.

I have tried working in different folders and allowing full disk access to Terminal.

Grateful for any ideas?

Many thanks,
Richard

<hr>

Obtaining posterior predicted time-observation profiles for each subject.
  |======================================================================| 100%

WARNING: error in extraction of cycle information; 'PMcycle' object not saved.

WARNING: error in extraction of final cycle parameter values; 'PMfinal' object not saved.

<hr>

> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.5.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Pmetrics_1.9.7

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13  magrittr_2.0.3   mclust_5.4.10    munsell_0.5.0   
 [5] tidyselect_1.1.2 colorspace_2.0-3 R6_2.5.1         rlang_1.0.4     
 [9] foreach_1.5.2    fansi_1.0.3      httr_1.4.3       dplyr_1.0.9     
[13] tools_4.2.1      grid_4.2.1       gtable_0.3.0     utf8_1.2.2      
[17] cli_3.3.0        DBI_1.1.3        cubelyr_1.0.1    iterators_1.0.14
[21] assertthat_0.2.1 tibble_3.1.8     lifecycle_1.0.1  gridExtra_2.3   
[25] tidyr_1.2.0      purrr_0.3.4      ggplot2_3.3.6    base64enc_0.1-3 
[29] vctrs_0.4.1      codetools_0.2-18 curl_4.3.2       glue_1.6.2      
[33] compiler_4.2.1   pillar_1.8.0     scales_1.2.0     generics_0.1.3  
[37] jsonlite_1.8.0   pkgconfig_2.0.3

**Comment by Siel** [comment]
Hi @richwilson17 , which version of Pmetrics are you using?

**Comment by richwilson17** [comment]
Hi Siel, 1.9.7

**Comment by Siel** [comment]
That is an issue with some functions that got deprecated in Pmetrics 1.9.7. I think we solved that issue some weeks ago but didn't icrease the version number.

Could you reinstall Pmetrics 1.9.7 using `devtools::install_github("LAPKB/Pmetrics")` or switch to Pmetrics 2.0 using `devtools::install_github("LAPKB/Pmetrics@Version2")` and report back?

Thank you!

**Comment by richwilson17** [comment]
Hi Siel. Reinstall 1.9.7 and successful build is presenting the same error. Switch to 2.0 is causing a new problem with gfortran which I'm not sure how to fix? Is there a change to where 2.0 looks for gfortran

<hr>

> PMbuild()
Pmetrics cannot find required compiled binary files.
Pmetrics cannot detect gfortran and will attempt to download and install all components.

<hr>

I am running a manual install of GNU Fortran (GCC) 12.1.0 (from the executable by fxcoudert) and command line tools.

**Comment by Siel** [comment]
@richwilson17 , could you paste the full error message please?

That message is normal, it will happen every time you install Pmetrics. If you’re on windows closing and opening again R studio should help (windows has problems picking up the right path for gfortran)

**Comment by richwilson17** [comment]
OK, thanks Siel. 1.9.7 is able to find it and builds fine. I'm running macOS on Apple silicon. Full error message below from 2.0. Have tried restarting R and OS. And reinstalling the package.

<hr>

> devtools::install_github("LAPKB/Pmetrics@Version2")
Downloading GitHub repo LAPKB/Pmetrics@Version2
✔  checking for file ‘/private/var/folders/tc/g307kcxd3533dz2ftn9qczqm0000gn/T/RtmpTkYiZU/remotes36f27879dca/LAPKB-Pmetrics-479eaf8/DESCRIPTION’ ...
─  preparing ‘Pmetrics’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Pmetrics_2.0.0.tar.gz’
   
* installing *source* package ‘Pmetrics’ ...
** using staged installation
** libs
clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c knn.cpp -o knn.o
clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c registerDynamicSymbol.cpp -o registerDynamicSymbol.o
clang++ -arch arm64 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o Pmetrics.so knn.o registerDynamicSymbol.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/00LOCK-Pmetrics/00new/Pmetrics/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (Pmetrics)

<hr>

> library(Pmetrics)

Welcome to Pmetrics, version 2.0.0.
Use PMmanual() or visit the LAPK website at http://www.lapk.org/pmetrics.php for help.
The Pmetrics forum is back! Click the tab at www.lapk.org for questions, tips and bug reports.

Follow Pmetrics tweets at https://twitter.com/USCLAPK.


CRITICAL: Execute PMbuild() in R to complete Pmetrics installation.


Attaching package: ‘Pmetrics’

The following object is masked from ‘package:base’:

    range

> PMbuild()
Pmetrics cannot find required compiled binary files.
Pmetrics cannot detect gfortran and will attempt to download and install all components.
Do you agree? (Y/N)

**Comment by Siel** [comment]
Hi @richwilson17 , actually I'm not seeing any error in the logs you pasted here, it looks fine for a Version2 install

**Comment by richwilson17** [comment]
Hi @Siel. Does pmetrics 2.0 need the Homebrew package manager etc installing? The problem I have is that gfortran is already installed but PMbuild() can't locate it "cannot detect gfortran" and won't progress. I wasn't sure if I should be downloading Homebrew etc in addition to the one I have which seems to work fine for 1.9.7 - https://github.com/fxcoudert/gfortran-for-macOS/releases. Apologies if I am misunderstanding all this!

**Comment by Siel** [comment]
Hi @richwilson17 , The code to recognize fortran and to execute PMbuild() is exactly the same one on 1.9.7 and 2.0. That is the reason its weird that you're getting an error on 2.0. The only thing that crosses my mind is if you're using a ARM mac (M1 or M2), in that case it might happen that your rosetta environment is not grabbing the right path for gfortran

**Comment by richwilson17** [comment]
Hi @Siel. I removed the fxcoudert gfortran release and installed gcc via Homebrew. Pmetrics 2.0 builds fine and completes NPAG successfully. Posting in case anyone else runs into same problems during transition! Thanks again.

**Comment by Siel** [comment]
@richwilson17 Thanks for reporting back. I'm closing this issue.

**Comment by mshaer-pkpd** [comment]
Hi-
I am using Pmetrics 1.9.8, which should have all the updated features in v2.0, but still see the same error (PMcycle and PMfinal not saved) and the Convergence plots, Marginal plots, and Parameter values tabs are all empty in the html output and when loading the run using PMload. Any hints? Thanks

**Comment by mnneely** [comment]
V 1.9.8 is definitely not the same as 2.0. :) If you are not able to save objects it means the run bombed. Sometimes you can scroll back through the DOS window on Windows or the Terminal on Mac and see the error that caused the run to abort. In the /output folder, look for a file called NP_RF0001.TXT. If that isn't full of data or isn't there, the run failed. There might be information about the failure in the OUTT0001 file, also in /outputs.

**Comment by mshaer-pkpd** [comment]
The run didn't abort. It actually converged but the warning in the DOS window was "error in extraction of cycle information; PMcycle object not saved"
